window.App = {
  container: document.getElementById('view-container'),
  state:{conferenceId:localStorage.getItem(APP_SETTINGS.CONFERENCE_KEY)||'',lookups:null,currentConference:null,view:'dashboard'},
  async init(){
    document.getElementById('sandbox-hint').classList.toggle('hidden',!APP_SETTINGS.SANDBOX);
    document.getElementById('mode-badge').textContent=APP_SETTINGS.SANDBOX?'DEMONSTRAÇÃO':'PRODUÇÃO';
    document.getElementById('login-form').addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const d=Object.fromEntries(new FormData(e.target));await Auth.login(d.username,d.password);await this.start();}catch(err){UI.toast(err.message,'error');b.disabled=false;}});
    if(Auth.hasSession()){try{await this.start();}catch(err){Auth.clearSession();UI.toast('A sessão expirou. Inicie sessão novamente.','error');}}
  },
  async start(){if(!Auth.permissions.length)await Auth.refresh();document.getElementById('login-view').classList.add('hidden');document.getElementById('app-shell').classList.remove('hidden');document.getElementById('current-user-name').textContent=Auth.user?.nome||'';document.getElementById('current-user-role').textContent=Auth.user?.perfil_nome||Auth.user?.perfil_id||'';document.getElementById('logout-btn').onclick=()=>Auth.logout();document.getElementById('refresh-btn').onclick=()=>this.render(this.state.view);document.getElementById('menu-btn').onclick=()=>document.getElementById('sidebar').classList.toggle('open');document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{this.render(b.dataset.view);document.getElementById('sidebar').classList.remove('open');});this.applyNavigationPermissions();await this.loadLookups();this.render(document.querySelector('.nav-item:not(.hidden)')?.dataset.view||'dashboard');},
  applyNavigationPermissions(){const required={dashboard:'dashboard.ver',conference:'conferencias.ver',participants:'participantes.ver',credentials:'credenciais.ver',attendance:'presencas.ver',materials:'materiais.ver',payments:'pagamentos.ver',sessions:'sessoes.ver',intervenients:'sessoes.ver',users:'utilizadores.gerir'};document.querySelectorAll('.nav-item').forEach(item=>item.classList.toggle('hidden',!Auth.can(required[item.dataset.view])));},
  async loadLookups(){this.state.lookups=await Api.request('lookups.get',{});if(!this.state.conferenceId||!this.state.lookups.conferences.some(x=>x.id_conferencia===this.state.conferenceId))this.state.conferenceId=this.state.lookups.selectedConferenceId||this.state.lookups.conferences[0]?.id_conferencia||'';this.state.currentConference=this.state.lookups.conferences.find(x=>x.id_conferencia===this.state.conferenceId)||null;localStorage.setItem(APP_SETTINGS.CONFERENCE_KEY,this.state.conferenceId);const s=document.getElementById('conference-switcher');s.innerHTML=this.state.lookups.conferences.length?this.state.lookups.conferences.map(x=>UI.option(x.id_conferencia,x.nome,this.state.conferenceId)).join(''):'<option value="">Sem conferência</option>';s.onchange=e=>{this.state.conferenceId=e.target.value;this.state.currentConference=this.state.lookups.conferences.find(x=>x.id_conferencia===e.target.value)||null;localStorage.setItem(APP_SETTINGS.CONFERENCE_KEY,e.target.value);this.render(this.state.view);};},
  async render(view){this.state.view=view;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));this.container.innerHTML='<div class="empty">A carregar…</div>';try{if(!Views[view])throw new Error('Vista não encontrada.');await Views[view]();}catch(err){this.container.innerHTML=`<div class="card panel"><h3>Não foi possível carregar</h3><p class="muted">${UI.escape(err.message)}</p><button class="btn btn-primary" onclick="App.render('${view}')">Tentar novamente</button></div>`;UI.toast(err.message,'error');}}
};
document.addEventListener('DOMContentLoaded',()=>App.init());
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js').catch(()=>{}));
