(function () {
  const KEY = 'cmnm_sandbox_db_v2_1';
  const now = new Date();
  const date = (offset) => new Date(now.getTime()+offset*86400000).toISOString().slice(0,10);
  const initial = {
    conferences:[{id_conferencia:'CONF-DEMO',codigo:'CMNM-2026',nome:'Conferência Nacional de Mulheres Nazarenas — 2026',tema:'Mulheres firmes na fé e no serviço',lema:'Chamadas para servir',texto_biblico:'Ester 4:14',local:'Cidade da Matola',data_inicio:date(20),data_fim:date(22),inscricoes_inicio:date(-30),inscricoes_fim:date(15),valor_inscricao:1500,capacidade:500,estado:'INSCRICOES_ABERTAS',contacto_nome:'Comissão Nacional',contacto_telefone:'840000000',activo:true}],
    districts:[{id_distrito:'DIST-MATOLA',codigo:'MAT',nome:'Distrito da Matola',activo:true},{id_distrito:'DIST-MAPUTO',codigo:'MAP',nome:'Distrito de Maputo',activo:true},{id_distrito:'DIST-GAZA',codigo:'GAZ',nome:'Distrito de Gaza',activo:true}],
    churches:[{id_igreja:'IGR-INFULENE',id_distrito:'DIST-MATOLA',nome:'Igreja do Nazareno em Infulene',activo:true},{id_igreja:'IGR-TCHUMENE',id_distrito:'DIST-MATOLA',nome:'Igreja do Nazareno em Tchumene',activo:true},{id_igreja:'IGR-MAPUTO',id_distrito:'DIST-MAPUTO',nome:'Igreja do Nazareno em Maputo',activo:true}],
    categories:[{id_categoria:'DELEGADA',nome:'Delegada oficial',activo:true},{id_categoria:'PARTICIPANTE',nome:'Participante',activo:true},{id_categoria:'CONVIDADA',nome:'Convidada',activo:true},{id_categoria:'MODERADORA',nome:'Moderadora',activo:true},{id_categoria:'ORADORA',nome:'Oradora',activo:true}],
    chargeTypes:[{id_tipo_cobranca:'INSCRICAO',nome:'Inscrição',activo:true},{id_tipo_cobranca:'ALOJAMENTO',nome:'Alojamento',activo:true},{id_tipo_cobranca:'CAMISETA',nome:'Camiseta',activo:true},{id_tipo_cobranca:'OUTRO',nome:'Outro',activo:true}],
    profiles:[{id_perfil:'ADMIN_GERAL',nome:'Administradora geral',activo:true},{id_perfil:'SECRETARIA',nome:'Secretaria',activo:true},{id_perfil:'TESOURARIA',nome:'Tesouraria',activo:true},{id_perfil:'PROGRAMA',nome:'Coordenação do programa',activo:true}],
    users:[{id_utilizador:'USR-DEMO',nome:'Administradora de Demonstração',username:'admin',email:'admin@demo.local',perfil_id:'ADMIN_GERAL',perfil_nome:'Administradora geral',activo:true}],
    participants:[
      {id_inscricao:'INS-1',id_participante:'PAR-1',id_conferencia:'CONF-DEMO',numero_inscricao:'CMNM-2026-00001',nome_completo:'Maria José Matola',telefone:'841234567',email:'maria@example.org',id_distrito:'DIST-MATOLA',distrito_nome:'Distrito da Matola',id_igreja:'IGR-INFULENE',igreja_nome:'Igreja do Nazareno em Infulene',id_categoria:'DELEGADA',categoria_nome:'Delegada oficial',total_devido:1500,total_pago:1500,saldo_pendente:0,estado_pagamento:'PAGO',estado_inscricao:'CONFIRMADA',necessita_alojamento:true,necessita_transporte:false},
      {id_inscricao:'INS-2',id_participante:'PAR-2',id_conferencia:'CONF-DEMO',numero_inscricao:'CMNM-2026-00002',nome_completo:'Ana Carla Nhampossa',telefone:'851234567',email:'ana@example.org',id_distrito:'DIST-MAPUTO',distrito_nome:'Distrito de Maputo',id_igreja:'IGR-MAPUTO',igreja_nome:'Igreja do Nazareno em Maputo',id_categoria:'PARTICIPANTE',categoria_nome:'Participante',total_devido:1500,total_pago:700,saldo_pendente:800,estado_pagamento:'PARCIAL',estado_inscricao:'SUBMETIDA',necessita_alojamento:false,necessita_transporte:true},
      {id_inscricao:'INS-3',id_participante:'PAR-3',id_conferencia:'CONF-DEMO',numero_inscricao:'CMNM-2026-00003',nome_completo:'Teresa Alberto Cossa',telefone:'861234567',email:'teresa@example.org',id_distrito:'DIST-MATOLA',distrito_nome:'Distrito da Matola',id_igreja:'IGR-TCHUMENE',igreja_nome:'Igreja do Nazareno em Tchumene',id_categoria:'CONVIDADA',categoria_nome:'Convidada',total_devido:0,total_pago:0,saldo_pendente:0,estado_pagamento:'ISENTO',estado_inscricao:'PRESENTE',necessita_alojamento:true,necessita_transporte:true}
    ],
    payments:[{id_pagamento:'PAG-1',id_conferencia:'CONF-DEMO',id_inscricao:'INS-1',participante_nome:'Maria José Matola',numero_inscricao:'CMNM-2026-00001',id_tipo_cobranca:'INSCRICAO',tipo_cobranca_nome:'Inscrição',valor:1500,metodo_pagamento:'M-PESA',referencia:'MP123456',data_pagamento:date(-2),estado:'CONFIRMADO',numero_recibo:'REC-CMNM-2026-000001'},{id_pagamento:'PAG-2',id_conferencia:'CONF-DEMO',id_inscricao:'INS-2',participante_nome:'Ana Carla Nhampossa',numero_inscricao:'CMNM-2026-00002',id_tipo_cobranca:'INSCRICAO',tipo_cobranca_nome:'Inscrição',valor:700,metodo_pagamento:'NUMERARIO',referencia:'',data_pagamento:date(-1),estado:'SUBMETIDO',numero_recibo:''}],
    intervenients:[{id_interveniente:'INT-1',nome:'Rev. Isabel Mucavele',tipo:'MODERADORA',titulo_funcao:'Coordenadora nacional',telefone:'840000001',email:'isabel@example.org',confirmacao:'CONFIRMADA',activo:true},{id_interveniente:'INT-2',nome:'Dra. Lúcia Macamo',tipo:'ORADORA',titulo_funcao:'Palestrante',telefone:'840000002',email:'lucia@example.org',confirmacao:'CONFIRMADA',activo:true}],
    sessions:[{id_sessao:'PROG-1',id_conferencia:'CONF-DEMO',titulo:'Culto de abertura',tipo:'ABERTURA',data:date(20),hora_inicio:'09:00',hora_fim:'10:30',local:'Auditório principal',capacidade:500,id_moderadora:'INT-1',moderadora_nome:'Rev. Isabel Mucavele',id_oradora:'INT-2',oradora_nome:'Dra. Lúcia Macamo',estado:'CONFIRMADA'},{id_sessao:'PROG-2',id_conferencia:'CONF-DEMO',titulo:'Liderança e serviço cristão',tipo:'PALESTRA',data:date(20),hora_inicio:'11:00',hora_fim:'12:30',local:'Auditório principal',capacidade:500,id_moderadora:'INT-1',moderadora_nome:'Rev. Isabel Mucavele',id_oradora:'INT-2',oradora_nome:'Dra. Lúcia Macamo',estado:'PROGRAMADA'}],
    accommodations:[{id_alojamento:'ALO-1',id_conferencia:'CONF-DEMO',nome:'Centro de Acolhimento Betânia',tipo:'INTERNATO',endereco:'Matola',responsavel:'Sara Mucavele',telefone:'840000010',capacidade:4,activo:true,observacoes:''}],
    accommodationAssignments:[{id_atribuicao:'AAT-1',id_alojamento:'ALO-1',id_inscricao:'INS-3',quarto:'Quarto 1',cama:'Cama A',data_entrada:date(20),data_saida:date(22),estado:'ATRIBUIDA',observacoes:''}],
    meals:[{id_refeicao:'REF-1',id_conferencia:'CONF-DEMO',nome:'Almoço do primeiro dia',tipo:'ALMOCO',data:date(20),hora_inicio:'12:30',hora_fim:'14:00',local:'Refeitório principal',fornecedor:'Comissão de Alimentação',responsavel:'Rosa Macamo',quantidade_prevista:500,estado:'PLANEADA',observacoes:''},{id_refeicao:'REF-2',id_conferencia:'CONF-DEMO',nome:'Jantar do primeiro dia',tipo:'JANTAR',data:date(20),hora_inicio:'18:30',hora_fim:'20:00',local:'Refeitório principal',fornecedor:'Comissão de Alimentação',responsavel:'Rosa Macamo',quantidade_prevista:500,estado:'PLANEADA',observacoes:''}],
    mealDeliveries:[{id_entrega_refeicao:'ERF-1',id_refeicao:'REF-1',id_inscricao:'INS-3',data_hora:new Date().toISOString(),observacoes:''}],
    transports:[{id_transporte:'TRA-1',id_conferencia:'CONF-DEMO',rota:'Maputo — Matola',ponto_partida:'Maputo Central',destino:'Local da conferência',data:date(20),hora:'07:00',viatura:'Autocarro 30 lugares',matricula:'ABC-12-34',motorista:'João Cossa',telefone:'840000020',capacidade:30,estado:'CONFIRMADO',observacoes:''}],
    transportAssignments:[{id_atribuicao:'ATR-1',id_transporte:'TRA-1',id_inscricao:'INS-2',ponto_embarque:'Maputo Central',estado:'ATRIBUIDA',observacoes:''}],
    certificates:[]
  };
  function load(){const raw=localStorage.getItem(KEY);if(raw)return JSON.parse(raw);localStorage.setItem(KEY,JSON.stringify(initial));return JSON.parse(JSON.stringify(initial));}
  function save(db){localStorage.setItem(KEY,JSON.stringify(db));}
  function id(prefix){return prefix+'-'+Math.random().toString(36).slice(2,10).toUpperCase();}
  const page=(items)=>({items,total:items.length,page:1,pageSize:500,pages:1});
  window.sandboxApi=async function(action,data){
    await new Promise(r=>setTimeout(r,180)); const db=load(); data=data||{};
    db.materials=db.materials||[]; db.deliveries=db.deliveries||[]; db.attendance=db.attendance||[];
    db.accommodations=db.accommodations||[]; db.accommodationAssignments=db.accommodationAssignments||[];
    db.meals=db.meals||[]; db.mealDeliveries=db.mealDeliveries||[];
    db.transports=db.transports||[]; db.transportAssignments=db.transportAssignments||[]; db.certificates=db.certificates||[];
    db.participants.forEach((p,index)=>{p.codigo_qr=p.codigo_qr||p.numero_inscricao;p.credencial_entregue=Boolean(p.credencial_entregue);if(index===0&&!p.necessidades_alimentares)p.necessidades_alimentares='Sem lactose';});
    if(action==='system.health')return{app:'Sandbox',version:'1.0.0',status:'online'};
    if(action==='auth.login'){if(data.username==='admin'&&data.password==='admin')return{token:'sandbox-token',expiresAt:date(1),user:db.users[0],permissions:['*']};throw new Error('Utilizador ou palavra-passe inválidos.');}
    if(action==='auth.me')return{user:db.users[0],permissions:['*']}; if(action==='auth.logout')return{loggedOut:true};
    if(action==='lookups.get')return{districts:db.districts,churches:db.churches,categories:db.categories,chargeTypes:db.chargeTypes,profiles:db.profiles,conferences:db.conferences,intervenients:db.intervenients,selectedConferenceId:db.conferences[0]?.id_conferencia||''};
    if(action==='conferences.list')return page(db.conferences);
    if(action==='conferences.save'){if(data.data_inicio&&data.data_fim&&data.data_fim<data.data_inicio)throw new Error('A data de encerramento não pode ser anterior à data de início da conferência.');if(data.inscricoes_inicio&&data.inscricoes_fim&&data.inscricoes_fim<data.inscricoes_inicio)throw new Error('A data de fim das inscrições não pode ser anterior à data de início das inscrições.');let r;if(data.id_conferencia){r=db.conferences.find(x=>x.id_conferencia===data.id_conferencia);Object.assign(r,data);}else{r={...data,id_conferencia:id('CONF'),activo:true};db.conferences.push(r);}save(db);return r;}
    if(action==='participants.list'){let rows=db.participants.filter(x=>!data.id_conferencia||x.id_conferencia===data.id_conferencia);if(data.search){const q=data.search.toLowerCase();rows=rows.filter(x=>[x.nome_completo,x.telefone,x.numero_inscricao,x.igreja_nome].some(v=>String(v||'').toLowerCase().includes(q)));}if(data.estado_inscricao)rows=rows.filter(x=>x.estado_inscricao===data.estado_inscricao);return page(rows);}
    if(action==='participants.create'){const d=db.districts.find(x=>x.id_distrito===data.id_distrito),c=db.churches.find(x=>x.id_igreja===data.id_igreja),cat=db.categories.find(x=>x.id_categoria===data.id_categoria);if(data.id_igreja&&(!d||!c||String(c.id_distrito)!==String(data.id_distrito)))throw new Error('A igreja seleccionada não pertence ao distrito indicado.');const n=db.participants.length+1;const number='CMNM-2026-'+String(n).padStart(5,'0');const r={...data,id_inscricao:id('INS'),id_participante:id('PAR'),numero_inscricao:number,codigo_qr:number,credencial_entregue:false,data_checkin:'',distrito_nome:d?.nome||'',igreja_nome:c?.nome||'',categoria_nome:cat?.nome||'',total_devido:Number(data.total_devido||1500),total_pago:0,saldo_pendente:Number(data.total_devido||1500),estado_pagamento:Number(data.total_devido||1500)>0?'PENDENTE':'ISENTO',estado_inscricao:data.estado_inscricao||'SUBMETIDA'};db.participants.push(r);save(db);return{participant:r,registration:r};}
    if(action==='participants.update'){const d=db.districts.find(x=>x.id_distrito===data.id_distrito),c=db.churches.find(x=>x.id_igreja===data.id_igreja),cat=db.categories.find(x=>x.id_categoria===data.id_categoria);if(data.id_igreja&&(!d||!c||String(c.id_distrito)!==String(data.id_distrito)))throw new Error('A igreja seleccionada não pertence ao distrito indicado.');const r=db.participants.find(x=>x.id_inscricao===data.id_inscricao);Object.assign(r,data,{distrito_nome:d?.nome||'',igreja_nome:c?.nome||'',categoria_nome:cat?.nome||data.id_categoria});save(db);return{updated:true};}
    if(action==='participants.setStatus'){const r=db.participants.find(x=>x.id_inscricao===data.id_inscricao);r.estado_inscricao=data.estado_inscricao;save(db);return r;}
    if(action==='participants.checkin'){const r=db.participants.find(x=>x.id_inscricao===data.id_inscricao);r.estado_inscricao='PRESENTE';r.data_checkin=new Date().toISOString();if(data.credencial_entregue!==undefined)r.credencial_entregue=Boolean(data.credencial_entregue);save(db);return r;}
    if(action==='payments.list'){let rows=db.payments.filter(x=>!data.id_conferencia||x.id_conferencia===data.id_conferencia);if(data.estado)rows=rows.filter(x=>x.estado===data.estado);return page(rows);}
    if(action==='payments.create'){const p=db.participants.find(x=>x.id_inscricao===data.id_inscricao);const r={...data,id_pagamento:id('PAG'),participante_nome:p?.nome_completo||'',numero_inscricao:p?.numero_inscricao||'',tipo_cobranca_nome:db.chargeTypes.find(x=>x.id_tipo_cobranca===data.id_tipo_cobranca)?.nome||data.descricao,valor:Number(data.valor),estado:'SUBMETIDO'};db.payments.push(r);save(db);return r;}
    if(action==='payments.confirm'){const r=db.payments.find(x=>x.id_pagamento===data.id_pagamento);r.estado='CONFIRMADO';r.numero_recibo=r.numero_recibo||'REC-DEMO-'+String(db.payments.indexOf(r)+1).padStart(6,'0');const p=db.participants.find(x=>x.id_inscricao===r.id_inscricao);if(p){p.total_pago=Number(p.total_pago||0)+Number(r.valor);p.saldo_pendente=Math.max(0,p.total_devido-p.total_pago);p.estado_pagamento=p.saldo_pendente===0?'PAGO':'PARCIAL';}save(db);return r;}
    if(action==='payments.reject'){const r=db.payments.find(x=>x.id_pagamento===data.id_pagamento);r.estado='REJEITADO';r.motivo_rejeicao=data.motivo_rejeicao;save(db);return r;}
    if(action==='sessions.list')return page(db.sessions.filter(x=>!data.id_conferencia||x.id_conferencia===data.id_conferencia));
    if(action==='sessions.save'){if(data.hora_inicio&&data.hora_fim&&data.hora_fim<=data.hora_inicio)throw new Error('A hora de término deve ser posterior à hora de início.');let r;if(data.id_sessao){r=db.sessions.find(x=>x.id_sessao===data.id_sessao);Object.assign(r,data);}else{r={...data,id_sessao:id('PROG')};db.sessions.push(r);}const m=db.intervenients.find(x=>x.id_interveniente===r.id_moderadora),o=db.intervenients.find(x=>x.id_interveniente===r.id_oradora);r.moderadora_nome=m?.nome||'';r.oradora_nome=o?.nome||'';save(db);return r;}
    if(action==='intervenients.list')return page(db.intervenients);
    if(action==='intervenients.save'){let r;if(data.id_interveniente){r=db.intervenients.find(x=>x.id_interveniente===data.id_interveniente);Object.assign(r,data);}else{r={...data,id_interveniente:id('INT'),activo:true};db.intervenients.push(r);}save(db);return r;}
    if(action==='users.list')return page(db.users);
    if(action==='users.create'){const r={...data,id_utilizador:id('USR'),perfil_nome:db.profiles.find(x=>x.id_perfil===data.perfil_id)?.nome||data.perfil_id,activo:true};delete r.password;db.users.push(r);save(db);return r;}
    if(action==='users.update'){const r=db.users.find(x=>x.id_utilizador===data.id_utilizador);Object.assign(r,data);save(db);return r;}
    if(action==='registrations.lookup'){const q=String(data.query||'').trim().toLowerCase();let rows=db.participants.filter(x=>x.id_conferencia===data.id_conferencia);const exact=rows.find(x=>[x.id_inscricao,x.codigo_qr,x.numero_inscricao].some(v=>String(v||'').toLowerCase()===q));rows=exact?[exact]:rows.filter(x=>[x.nome_completo,x.telefone,x.numero_inscricao,x.numero_documento,x.codigo_qr].some(v=>String(v||'').toLowerCase().includes(q))).slice(0,20);return{items:rows,total:rows.length};}
    if(action==='credentials.setDelivered'){const r=db.participants.find(x=>x.id_inscricao===data.id_inscricao);if(!r)throw new Error('Inscrição não encontrada.');r.credencial_entregue=Boolean(data.credencial_entregue);save(db);return r;}
    if(action==='credentials.checkin'){const q=String(data.query||'').toLowerCase();const r=db.participants.find(x=>x.id_conferencia===data.id_conferencia&&[x.id_inscricao,x.codigo_qr,x.numero_inscricao].some(v=>String(v||'').toLowerCase()===q));if(!r)throw new Error('Inscrição não encontrada.');r.estado_inscricao='PRESENTE';r.data_checkin=new Date().toISOString();if(data.credencial_entregue!==undefined)r.credencial_entregue=Boolean(data.credencial_entregue);save(db);return r;}
    if(action==='attendance.record'){const q=String(data.query||'').toLowerCase();const participant=db.participants.find(x=>x.id_conferencia===data.id_conferencia&&[x.id_inscricao,x.codigo_qr,x.numero_inscricao].some(v=>String(v||'').toLowerCase()===q));if(!participant)throw new Error('Inscrição não encontrada.');const open=db.attendance.find(x=>x.id_sessao===data.id_sessao&&x.id_inscricao===participant.id_inscricao&&!x.data_hora_saida);if(data.movimento==='ENTRADA'){if(open)return{status:'JA_REGISTADA',movimento:'ENTRADA',registration:participant,presence:open};const presence={id_presenca:id('PRE'),id_conferencia:data.id_conferencia,id_sessao:data.id_sessao,id_inscricao:participant.id_inscricao,data_hora_entrada:new Date().toISOString(),data_hora_saida:'',tipo:'SESSAO'};db.attendance.push(presence);save(db);return{status:'REGISTADA',movimento:'ENTRADA',registration:participant,presence};}if(!open)throw new Error('Não existe uma entrada aberta desta participante nesta sessão.');open.data_hora_saida=new Date().toISOString();save(db);return{status:'REGISTADA',movimento:'SAIDA',registration:participant,presence:open};}
    if(action==='attendance.list'){let rows=db.attendance.filter(x=>x.id_conferencia===data.id_conferencia&&(!data.id_sessao||x.id_sessao===data.id_sessao)).map(x=>{const p=db.participants.find(r=>r.id_inscricao===x.id_inscricao)||{};return{...x,...p};});return{...page(rows),summary:{total_registos:rows.length,presentes_agora:rows.filter(x=>!x.data_hora_saida).length,saidas_registadas:rows.filter(x=>x.data_hora_saida).length}};}
    if(action==='materials.list'){let rows=db.materials.filter(x=>x.id_conferencia===data.id_conferencia);return page(rows.map(x=>({...x,total_entregue:db.deliveries.filter(d=>d.id_material===x.id_material).reduce((sum,d)=>sum+Number(d.quantidade||0),0),stock_disponivel:Number(x.stock_actual||0)})));}
    if(action==='materials.save'){let r;if(data.id_material){r=db.materials.find(x=>x.id_material===data.id_material);const delivered=Number(r.stock_inicial||0)-Number(r.stock_actual||0);Object.assign(r,data,{stock_inicial:Number(data.stock_inicial||0),stock_actual:Number(data.stock_inicial||0)-delivered});}else{r={...data,id_material:id('MAT'),codigo:data.codigo||'MAT-'+String(db.materials.length+1).padStart(4,'0'),stock_inicial:Number(data.stock_inicial||0),stock_actual:Number(data.stock_inicial||0),activo:data.activo!==false};db.materials.push(r);}save(db);return r;}
    if(action==='materials.deliver'){const material=db.materials.find(x=>x.id_material===data.id_material);const p=db.participants.find(x=>x.id_inscricao===data.id_inscricao);const qty=Number(data.quantidade||1);if(!material||Number(material.stock_actual||0)<qty)throw new Error('Stock insuficiente.');const r={id_entrega:id('ENT'),id_material:data.id_material,id_inscricao:data.id_inscricao,quantidade:qty,data_entrega:new Date().toISOString(),material_nome:material.nome,material_tamanho:material.tamanho,nome_completo:p?.nome_completo||'',numero_inscricao:p?.numero_inscricao||'',distrito_nome:p?.distrito_nome||'',igreja_nome:p?.igreja_nome||''};db.deliveries.push(r);material.stock_actual=Number(material.stock_actual||0)-qty;save(db);return r;}
    if(action==='materials.deliveries'){const rows=db.deliveries.filter(d=>{const m=db.materials.find(x=>x.id_material===d.id_material);return m?.id_conferencia===data.id_conferencia;});return page(rows);}
    if(action==='accommodations.list'){
      const rows=db.accommodations.filter(x=>x.id_conferencia===data.id_conferencia).map(x=>{const occupied=db.accommodationAssignments.filter(a=>a.id_alojamento===x.id_alojamento&&['ATRIBUIDA','HOSPEDADA'].includes(a.estado)).length;return{...x,ocupadas:occupied,vagas:Math.max(0,Number(x.capacidade||0)-occupied)};});
      const needy=db.participants.filter(x=>x.id_conferencia===data.id_conferencia&&x.necessita_alojamento&&!['CANCELADA','RECUSADA'].includes(x.estado_inscricao));
      const assigned=new Set(db.accommodationAssignments.filter(x=>['ATRIBUIDA','HOSPEDADA'].includes(x.estado)).map(x=>x.id_inscricao));
      return{...page(rows),summary:{locais:rows.length,capacidade_total:rows.reduce((s,x)=>s+Number(x.capacidade||0),0),ocupadas:rows.reduce((s,x)=>s+Number(x.ocupadas||0),0),vagas:rows.reduce((s,x)=>s+Number(x.vagas||0),0),por_atribuir:needy.filter(x=>!assigned.has(x.id_inscricao)).length}};
    }
    if(action==='accommodations.save'){
      const capacity=Number(data.capacidade||0);if(capacity<1)throw new Error('A capacidade deve ser superior a zero.');let r;
      if(data.id_alojamento){r=db.accommodations.find(x=>x.id_alojamento===data.id_alojamento);if(!r)throw new Error('Local de alojamento não encontrado.');const occupied=db.accommodationAssignments.filter(a=>a.id_alojamento===r.id_alojamento&&['ATRIBUIDA','HOSPEDADA'].includes(a.estado)).length;if(capacity<occupied)throw new Error('A capacidade não pode ser inferior às vagas actualmente ocupadas.');Object.assign(r,data,{capacidade:capacity,activo:data.activo!==false&&String(data.activo)!=='false'});}else{r={...data,id_alojamento:id('ALO'),capacidade:capacity,activo:data.activo!==false&&String(data.activo)!=='false'};db.accommodations.push(r);}save(db);return r;
    }
    if(action==='accommodations.assignments'){
      const rows=db.accommodationAssignments.map(a=>{const place=db.accommodations.find(x=>x.id_alojamento===a.id_alojamento)||{};const p=db.participants.find(x=>x.id_inscricao===a.id_inscricao)||{};return{...a,id_conferencia:place.id_conferencia,alojamento_nome:place.nome||'',alojamento_tipo:place.tipo||'',nome_completo:p.nome_completo||'',numero_inscricao:p.numero_inscricao||'',telefone:p.telefone||'',distrito_nome:p.distrito_nome||'',igreja_nome:p.igreja_nome||''};}).filter(x=>x.id_conferencia===data.id_conferencia);return page(rows);
    }
    if(action==='accommodations.assign'){
      if(data.data_entrada&&data.data_saida&&data.data_saida<data.data_entrada)throw new Error('A data de saída não pode ser anterior à data de entrada.');const place=db.accommodations.find(x=>x.id_alojamento===data.id_alojamento&&x.id_conferencia===data.id_conferencia);if(!place)throw new Error('Local de alojamento não encontrado.');const active=db.accommodationAssignments.filter(x=>x.id_alojamento===place.id_alojamento&&['ATRIBUIDA','HOSPEDADA'].includes(x.estado));if(active.length>=Number(place.capacidade||0))throw new Error('O local de alojamento já atingiu a capacidade máxima.');const existing=db.accommodationAssignments.find(x=>x.id_inscricao===data.id_inscricao&&['ATRIBUIDA','HOSPEDADA'].includes(x.estado));if(existing)throw new Error('A participante já possui alojamento atribuído.');const r={...data,id_atribuicao:id('AAT'),estado:'ATRIBUIDA',criado_em:new Date().toISOString()};db.accommodationAssignments.push(r);save(db);return r;
    }
    if(action==='accommodations.setStatus'){const r=db.accommodationAssignments.find(x=>x.id_atribuicao===data.id_atribuicao);if(!r)throw new Error('Atribuição não encontrada.');r.estado=data.estado;save(db);return r;}
    if(action==='meals.list'){
      const rows=db.meals.filter(x=>x.id_conferencia===data.id_conferencia).map(x=>({...x,servidas:db.mealDeliveries.filter(d=>d.id_refeicao===x.id_refeicao).length}));return{...page(rows),summary:{refeicoes:rows.length,quantidade_prevista:rows.reduce((s,x)=>s+Number(x.quantidade_prevista||0),0),servidas:rows.reduce((s,x)=>s+Number(x.servidas||0),0)}};
    }
    if(action==='meals.save'){
      if(data.hora_inicio&&data.hora_fim&&data.hora_fim<=data.hora_inicio)throw new Error('A hora de término deve ser posterior à hora de início.');let r;if(data.id_refeicao){r=db.meals.find(x=>x.id_refeicao===data.id_refeicao);if(!r)throw new Error('Refeição não encontrada.');Object.assign(r,data,{quantidade_prevista:Number(data.quantidade_prevista||0)});}else{r={...data,id_refeicao:id('REF'),quantidade_prevista:Number(data.quantidade_prevista||0)};db.meals.push(r);}save(db);return r;
    }
    if(action==='meals.serve'){
      const meal=db.meals.find(x=>x.id_refeicao===data.id_refeicao&&x.id_conferencia===data.id_conferencia);if(!meal)throw new Error('Refeição não encontrada.');const existing=db.mealDeliveries.find(x=>x.id_refeicao===data.id_refeicao&&x.id_inscricao===data.id_inscricao);if(existing)throw new Error('Esta refeição já foi registada para a participante.');const r={id_entrega_refeicao:id('ERF'),id_refeicao:data.id_refeicao,id_inscricao:data.id_inscricao,data_hora:new Date().toISOString(),observacoes:data.observacoes||''};db.mealDeliveries.push(r);save(db);return{alreadyServed:false,delivery:r,registration:db.participants.find(x=>x.id_inscricao===data.id_inscricao)||{}};
    }
    if(action==='meals.deliveries'){
      const rows=db.mealDeliveries.map(d=>{const meal=db.meals.find(x=>x.id_refeicao===d.id_refeicao)||{};const p=db.participants.find(x=>x.id_inscricao===d.id_inscricao)||{};return{...d,id_conferencia:meal.id_conferencia,refeicao_nome:meal.nome||'',refeicao_tipo:meal.tipo||'',nome_completo:p.nome_completo||'',numero_inscricao:p.numero_inscricao||'',distrito_nome:p.distrito_nome||'',igreja_nome:p.igreja_nome||'',necessidades_alimentares:p.necessidades_alimentares||''};}).filter(x=>x.id_conferencia===data.id_conferencia);return page(rows);
    }
    if(action==='meals.dietary'){return page(db.participants.filter(x=>x.id_conferencia===data.id_conferencia&&String(x.necessidades_alimentares||'').trim()));}
    if(action==='transport.list'){
      const rows=db.transports.filter(x=>x.id_conferencia===data.id_conferencia).map(x=>{const passengers=db.transportAssignments.filter(a=>a.id_transporte===x.id_transporte&&['ATRIBUIDA','EMBARCADA'].includes(a.estado)).length;return{...x,passageiros:passengers,vagas:Math.max(0,Number(x.capacidade||0)-passengers)};});const needy=db.participants.filter(x=>x.id_conferencia===data.id_conferencia&&x.necessita_transporte&&!['CANCELADA','RECUSADA'].includes(x.estado_inscricao));const assigned=new Set(db.transportAssignments.filter(x=>['ATRIBUIDA','EMBARCADA'].includes(x.estado)).map(x=>x.id_inscricao));return{...page(rows),summary:{rotas:rows.length,capacidade_total:rows.reduce((s,x)=>s+Number(x.capacidade||0),0),passageiros:rows.reduce((s,x)=>s+Number(x.passageiros||0),0),vagas:rows.reduce((s,x)=>s+Number(x.vagas||0),0),por_atribuir:needy.filter(x=>!assigned.has(x.id_inscricao)).length}};
    }
    if(action==='transport.save'){const capacity=Number(data.capacidade||0);if(capacity<1)throw new Error('A capacidade deve ser superior a zero.');let r;if(data.id_transporte){r=db.transports.find(x=>x.id_transporte===data.id_transporte);if(!r)throw new Error('Rota não encontrada.');const used=db.transportAssignments.filter(a=>a.id_transporte===r.id_transporte&&['ATRIBUIDA','EMBARCADA'].includes(a.estado)).length;if(capacity<used)throw new Error('A capacidade não pode ser inferior ao número de passageiras atribuídas.');Object.assign(r,data,{capacidade:capacity});}else{r={...data,id_transporte:id('TRA'),capacidade:capacity};db.transports.push(r);}save(db);return r;}
    if(action==='transport.assignments'){
      const rows=db.transportAssignments.map(a=>{const route=db.transports.find(x=>x.id_transporte===a.id_transporte)||{};const p=db.participants.find(x=>x.id_inscricao===a.id_inscricao)||{};return{...a,id_conferencia:route.id_conferencia,rota:route.rota||'',ponto_partida:route.ponto_partida||'',destino:route.destino||'',data:route.data||'',hora:route.hora||'',nome_completo:p.nome_completo||'',numero_inscricao:p.numero_inscricao||'',distrito_nome:p.distrito_nome||'',igreja_nome:p.igreja_nome||''};}).filter(x=>x.id_conferencia===data.id_conferencia);return page(rows);
    }
    if(action==='transport.assign'){
      const route=db.transports.find(x=>x.id_transporte===data.id_transporte&&x.id_conferencia===data.id_conferencia);if(!route)throw new Error('Rota não encontrada.');const active=db.transportAssignments.filter(x=>x.id_transporte===route.id_transporte&&['ATRIBUIDA','EMBARCADA'].includes(x.estado));if(active.length>=Number(route.capacidade||0))throw new Error('A rota já atingiu a capacidade máxima.');const duplicate=db.transportAssignments.find(x=>x.id_transporte===route.id_transporte&&x.id_inscricao===data.id_inscricao&&['ATRIBUIDA','EMBARCADA'].includes(x.estado));if(duplicate)throw new Error('A participante já está atribuída a esta rota.');const r={...data,id_atribuicao:id('ATR'),estado:'ATRIBUIDA',criado_em:new Date().toISOString()};db.transportAssignments.push(r);save(db);return r;
    }
    if(action==='transport.setAssignmentStatus'){const r=db.transportAssignments.find(x=>x.id_atribuicao===data.id_atribuicao);if(!r)throw new Error('Atribuição não encontrada.');r.estado=data.estado;save(db);return r;}
    if(action==='certificates.list'){
      const rows=db.certificates.map(c=>{const p=db.participants.find(x=>x.id_inscricao===c.id_inscricao)||{};return{...c,nome_completo:p.nome_completo||'',numero_inscricao:p.numero_inscricao||'',distrito_nome:p.distrito_nome||'',igreja_nome:p.igreja_nome||''};}).filter(x=>x.id_conferencia===data.id_conferencia);return page(rows);
    }
    if(action==='certificates.generate'){
      const p=db.participants.find(x=>x.id_inscricao===data.id_inscricao&&x.id_conferencia===data.id_conferencia);if(!p)throw new Error('Inscrição não encontrada.');if(data.exigir_presenca!==false&&!p.data_checkin&&p.estado_inscricao!=='PRESENTE')throw new Error('A participante ainda não possui check-in na conferência.');const type=data.tipo||'PARTICIPACAO';const existing=db.certificates.find(x=>x.id_conferencia===data.id_conferencia&&x.id_inscricao===data.id_inscricao&&x.tipo===type&&x.estado==='EMITIDO');if(existing&&!data.regenerar)return{...existing,alreadyExists:true};if(existing&&data.regenerar)existing.estado='SUBSTITUIDO';const seq=db.certificates.length+1;const r={id_certificado:id('CER'),id_conferencia:data.id_conferencia,id_inscricao:data.id_inscricao,tipo:type,codigo:'CERT-DEMO-'+String(seq).padStart(6,'0'),ficheiro_url:'',data_emissao:new Date().toISOString(),estado:'EMITIDO'};db.certificates.push(r);save(db);return r;
    }
    if(action==='certificates.generateBatch'){
      const limit=Math.min(25,Math.max(1,Number(data.limite||10)));const eligible=db.participants.filter(x=>x.id_conferencia===data.id_conferencia&&!['CANCELADA','RECUSADA'].includes(x.estado_inscricao)&&(data.exigir_presenca===false||x.data_checkin||x.estado_inscricao==='PRESENTE')).slice(0,limit);let emitted=0,ignored=0;for(const p of eligible){const type=data.tipo||'PARTICIPACAO';const existing=db.certificates.find(x=>x.id_conferencia===data.id_conferencia&&x.id_inscricao===p.id_inscricao&&x.tipo===type&&x.estado==='EMITIDO');if(existing&&!data.regenerar){ignored++;continue;}if(existing)existing.estado='SUBSTITUIDO';db.certificates.push({id_certificado:id('CER'),id_conferencia:data.id_conferencia,id_inscricao:p.id_inscricao,tipo:type,codigo:'CERT-DEMO-'+String(db.certificates.length+1).padStart(6,'0'),ficheiro_url:'',data_emissao:new Date().toISOString(),estado:'EMITIDO'});emitted++;}save(db);return{emitidos:emitted,ignorados:ignored,erros:[],limite:limit};
    }
    if(action==='reports.catalog')return[
      {id:'RESUMO_EXECUTIVO',nome:'Resumo executivo',grupo:'Geral',descricao:'Indicadores consolidados da conferência.',filtros:['periodo']},
      {id:'PARTICIPANTES_GERAL',nome:'Lista geral de participantes',grupo:'Participantes',descricao:'Inscrições, contactos, proveniência e situação financeira.',filtros:['distrito','igreja','categoria','estado_inscricao','estado_pagamento','periodo','pesquisa']},
      {id:'PARTICIPANTES_DISTRITO',nome:'Participantes por distrito',grupo:'Participantes',descricao:'Totais e valores consolidados por distrito.',filtros:['distrito','estado_inscricao','periodo']},
      {id:'FINANCEIRO_PAGAMENTOS',nome:'Movimentos de pagamentos',grupo:'Finanças',descricao:'Pagamentos registados, métodos, referências e recibos.',filtros:['distrito','igreja','estado','metodo','tipo_cobranca','periodo','pesquisa']},
      {id:'FINANCEIRO_PENDENCIAS',nome:'Valores pendentes',grupo:'Finanças',descricao:'Participantes com saldo por regularizar.',filtros:['distrito','igreja','categoria','periodo','pesquisa']},
      {id:'FINANCEIRO_RECONCILIACAO',nome:'Reconciliação financeira',grupo:'Finanças',descricao:'Comparação entre valores devidos, pagamentos confirmados e saldo.',filtros:['distrito','igreja','periodo','pesquisa']},
      {id:'SESSOES_PROGRAMA',nome:'Programa e sessões',grupo:'Programa',descricao:'Agenda, locais, capacidade, moderadoras e oradoras.',filtros:['estado','periodo','pesquisa']},
      {id:'PRESENCAS_GERAL',nome:'Check-in geral',grupo:'Presenças',descricao:'Participantes presentes e ausentes na conferência.',filtros:['distrito','igreja','estado_presenca','pesquisa']},
      {id:'PRESENCAS_SESSAO',nome:'Presenças por sessão',grupo:'Presenças',descricao:'Entradas e saídas registadas nas sessões.',filtros:['sessao','distrito','igreja','periodo','pesquisa']},
      {id:'ALOJAMENTO_OCUPACAO',nome:'Ocupação dos alojamentos',grupo:'Logística',descricao:'Atribuições, quartos, camas e estados de hospedagem.',filtros:['alojamento','distrito','igreja','estado','pesquisa']},
      {id:'ALIMENTACAO_SERVICOS',nome:'Refeições servidas',grupo:'Logística',descricao:'Entregas de refeições e necessidades alimentares.',filtros:['refeicao','distrito','igreja','periodo','pesquisa']},
      {id:'TRANSPORTE_PASSAGEIRAS',nome:'Transportes e passageiras',grupo:'Logística',descricao:'Rotas, embarques e participantes atribuídas.',filtros:['transporte','distrito','igreja','estado','periodo','pesquisa']},
      {id:'MATERIAIS_ENTREGAS',nome:'Materiais entregues',grupo:'Logística',descricao:'Entregas por material e participante.',filtros:['material','distrito','igreja','periodo','pesquisa']},
      {id:'CERTIFICADOS_EMITIDOS',nome:'Certificados emitidos',grupo:'Certificados',descricao:'Certificados por participante, tipo e estado.',filtros:['distrito','igreja','tipo_certificado','estado','periodo','pesquisa']}
    ];
    if(action==='reports.options')return{
      sessions:db.sessions.filter(x=>x.id_conferencia===data.id_conferencia).map(x=>({id:x.id_sessao,nome:x.titulo,data:x.data,hora:x.hora_inicio})),
      accommodations:db.accommodations.filter(x=>x.id_conferencia===data.id_conferencia).map(x=>({id:x.id_alojamento,nome:x.nome})),
      meals:db.meals.filter(x=>x.id_conferencia===data.id_conferencia).map(x=>({id:x.id_refeicao,nome:x.nome,data:x.data})),
      transports:db.transports.filter(x=>x.id_conferencia===data.id_conferencia).map(x=>({id:x.id_transporte,nome:x.rota,data:x.data})),
      materials:db.materials.filter(x=>x.id_conferencia===data.id_conferencia).map(x=>({id:x.id_material,nome:x.nome}))
    };
    if(action==='reports.generate'){
      const conf=db.conferences.find(x=>x.id_conferencia===data.id_conferencia)||db.conferences[0]||{};
      const regs=db.participants.filter(x=>x.id_conferencia===data.id_conferencia)
        .filter(x=>!data.id_distrito||x.id_distrito===data.id_distrito)
        .filter(x=>!data.id_igreja||x.id_igreja===data.id_igreja)
        .filter(x=>!data.id_categoria||x.id_categoria===data.id_categoria)
        .filter(x=>!data.estado_inscricao||x.estado_inscricao===data.estado_inscricao)
        .filter(x=>!data.estado_pagamento||x.estado_pagamento===data.estado_pagamento)
        .filter(x=>!data.search||[x.nome_completo,x.numero_inscricao,x.telefone,x.distrito_nome,x.igreja_nome].join(' ').toLowerCase().includes(String(data.search).toLowerCase()));
      const map=Object.fromEntries(regs.map(x=>[x.id_inscricao,x]));
      const col=(key,label,type='text')=>({key,label,type});
      const sum=(label,value,type='number')=>({label,value,type});
      const result={tipo:data.tipo,titulo:'Relatório',descricao:'',conferencia:{id_conferencia:conf.id_conferencia,codigo:conf.codigo,nome:conf.nome,local:conf.local,data_inicio:conf.data_inicio,data_fim:conf.data_fim},gerado_em:new Date().toISOString(),gerado_por:'Administradora de Demonstração',filtros_aplicados:[],rows:[],columns:[],summary:[],chart:[],truncado:false};
      if(data.tipo==='RESUMO_EXECUTIVO'){
        const collected=db.payments.filter(x=>x.id_conferencia===data.id_conferencia&&x.estado==='CONFIRMADO').reduce((a,x)=>a+Number(x.valor||0),0);const due=regs.reduce((a,x)=>a+Number(x.total_devido||0),0);const pending=regs.reduce((a,x)=>a+Number(x.saldo_pendente||0),0);
        result.titulo='Resumo executivo da conferência';result.columns=[col('indicador','Indicador'),col('valor','Valor','mixed'),col('observacao','Observação')];result.rows=[{indicador:'Participantes registadas',valor:regs.length,observacao:'Total de inscrições'},{indicador:'Check-ins realizados',valor:regs.filter(x=>x.data_checkin||x.estado_inscricao==='PRESENTE').length,observacao:'Presença geral'},{indicador:'Total devido',valor:due,tipo_valor:'money',observacao:'Valor previsto'},{indicador:'Total arrecadado',valor:collected,tipo_valor:'money',observacao:due?Math.round(collected/due*100)+'% arrecadado':'0%'},{indicador:'Saldo pendente',valor:pending,tipo_valor:'money',observacao:'Valor por regularizar'}];result.summary=[sum('Participantes',regs.length),sum('Arrecadado',collected,'money'),sum('Pendente',pending,'money'),sum('Presentes',regs.filter(x=>x.data_checkin||x.estado_inscricao==='PRESENTE').length)];
      }else if(data.tipo==='PARTICIPANTES_GERAL'){
        result.titulo='Lista geral de participantes';result.columns=[col('numero_inscricao','N.º de inscrição'),col('nome_completo','Participante'),col('distrito','Distrito'),col('igreja','Igreja'),col('categoria','Categoria'),col('telefone','Telefone'),col('estado_inscricao','Estado da inscrição','status'),col('estado_pagamento','Pagamento','status'),col('total_devido','Devido','money'),col('total_pago','Pago','money'),col('saldo_pendente','Pendente','money')];result.rows=regs.map(x=>({numero_inscricao:x.numero_inscricao,nome_completo:x.nome_completo,distrito:x.distrito_nome,igreja:x.igreja_nome,categoria:x.categoria_nome,telefone:x.telefone,estado_inscricao:x.estado_inscricao,estado_pagamento:x.estado_pagamento,total_devido:x.total_devido,total_pago:x.total_pago,saldo_pendente:x.saldo_pendente}));result.summary=[sum('Participantes',result.rows.length),sum('Total devido',result.rows.reduce((a,x)=>a+Number(x.total_devido||0),0),'money'),sum('Total pago',result.rows.reduce((a,x)=>a+Number(x.total_pago||0),0),'money'),sum('Saldo pendente',result.rows.reduce((a,x)=>a+Number(x.saldo_pendente||0),0),'money')];
      }else if(data.tipo==='PARTICIPANTES_DISTRITO'){
        const groups={};regs.forEach(x=>{const k=x.distrito_nome||'Sem distrito';groups[k]=groups[k]||{distrito:k,total:0,confirmadas:0,presentes:0,devido:0,pago:0,pendente:0};const g=groups[k];g.total++;if(['CONFIRMADA','PRESENTE'].includes(x.estado_inscricao))g.confirmadas++;if(x.data_checkin||x.estado_inscricao==='PRESENTE')g.presentes++;g.devido+=Number(x.total_devido||0);g.pago+=Number(x.total_pago||0);g.pendente+=Number(x.saldo_pendente||0)});result.titulo='Participantes por distrito';result.columns=[col('distrito','Distrito'),col('total','Participantes','number'),col('confirmadas','Confirmadas','number'),col('presentes','Presentes','number'),col('devido','Devido','money'),col('pago','Pago','money'),col('pendente','Pendente','money')];result.rows=Object.values(groups);result.summary=[sum('Distritos',result.rows.length),sum('Participantes',regs.length),sum('Total pago',result.rows.reduce((a,x)=>a+x.pago,0),'money'),sum('Saldo pendente',result.rows.reduce((a,x)=>a+x.pendente,0),'money')];result.chart=result.rows.map(x=>({label:x.distrito,value:x.total}));
      }else if(data.tipo==='FINANCEIRO_PAGAMENTOS'){
        let rows=db.payments.filter(x=>x.id_conferencia===data.id_conferencia&&map[x.id_inscricao]);if(data.estado)rows=rows.filter(x=>x.estado===data.estado);if(data.metodo_pagamento)rows=rows.filter(x=>x.metodo_pagamento===data.metodo_pagamento);result.titulo='Movimentos de pagamentos';result.columns=[col('data_pagamento','Data','date'),col('numero_inscricao','Inscrição'),col('participante','Participante'),col('valor','Valor','money'),col('metodo','Método'),col('referencia','Referência'),col('estado','Estado','status'),col('recibo','Recibo')];result.rows=rows.map(x=>({data_pagamento:x.data_pagamento,numero_inscricao:map[x.id_inscricao].numero_inscricao,participante:map[x.id_inscricao].nome_completo,valor:x.valor,metodo:x.metodo_pagamento,referencia:x.referencia,estado:x.estado,recibo:x.numero_recibo}));result.summary=[sum('Movimentos',result.rows.length),sum('Confirmados',result.rows.filter(x=>x.estado==='CONFIRMADO').length),sum('Valor confirmado',result.rows.filter(x=>x.estado==='CONFIRMADO').reduce((a,x)=>a+Number(x.valor||0),0),'money'),sum('Valor submetido',result.rows.filter(x=>x.estado==='SUBMETIDO').reduce((a,x)=>a+Number(x.valor||0),0),'money')];
      }else if(data.tipo==='FINANCEIRO_PENDENCIAS'||data.tipo==='FINANCEIRO_RECONCILIACAO'){
        result.titulo=data.tipo==='FINANCEIRO_PENDENCIAS'?'Valores pendentes':'Reconciliação financeira';result.columns=[col('numero_inscricao','Inscrição'),col('participante','Participante'),col('distrito','Distrito'),col('igreja','Igreja'),col('total_devido','Devido','money'),col('total_pago','Pago','money'),col('saldo_pendente','Pendente','money')];result.rows=regs.filter(x=>data.tipo==='FINANCEIRO_RECONCILIACAO'||Number(x.saldo_pendente||0)>0).map(x=>({numero_inscricao:x.numero_inscricao,participante:x.nome_completo,distrito:x.distrito_nome,igreja:x.igreja_nome,total_devido:x.total_devido,total_pago:x.total_pago,saldo_pendente:x.saldo_pendente}));result.summary=[sum('Inscrições',result.rows.length),sum('Total devido',result.rows.reduce((a,x)=>a+Number(x.total_devido||0),0),'money'),sum('Total pago',result.rows.reduce((a,x)=>a+Number(x.total_pago||0),0),'money'),sum('Saldo pendente',result.rows.reduce((a,x)=>a+Number(x.saldo_pendente||0),0),'money')];
      }else if(data.tipo==='SESSOES_PROGRAMA'){
        result.titulo='Programa e sessões';result.columns=[col('data','Data','date'),col('hora_inicio','Início'),col('hora_fim','Fim'),col('titulo','Sessão'),col('tipo','Tipo'),col('local','Local'),col('capacidade','Capacidade','number'),col('moderadora','Moderadora'),col('oradora','Oradora'),col('estado','Estado','status')];result.rows=db.sessions.filter(x=>x.id_conferencia===data.id_conferencia).map(x=>({...x,moderadora:x.moderadora_nome||'',oradora:x.oradora_nome||''}));result.summary=[sum('Sessões',result.rows.length),sum('Capacidade',result.rows.reduce((a,x)=>a+Number(x.capacidade||0),0)),sum('Sem moderadora',result.rows.filter(x=>!x.moderadora).length),sum('Canceladas',result.rows.filter(x=>x.estado==='CANCELADA').length)];
      }else if(data.tipo==='PRESENCAS_GERAL'){
        result.titulo='Check-in geral';result.columns=[col('numero_inscricao','Inscrição'),col('participante','Participante'),col('distrito','Distrito'),col('igreja','Igreja'),col('situacao','Presença','status'),col('data_checkin','Check-in','datetime')];result.rows=regs.map(x=>({numero_inscricao:x.numero_inscricao,participante:x.nome_completo,distrito:x.distrito_nome,igreja:x.igreja_nome,situacao:x.data_checkin||x.estado_inscricao==='PRESENTE'?'PRESENTE':'AUSENTE',data_checkin:x.data_checkin})).filter(x=>!data.estado_presenca||x.situacao===data.estado_presenca);result.summary=[sum('Participantes',result.rows.length),sum('Presentes',result.rows.filter(x=>x.situacao==='PRESENTE').length),sum('Ausentes',result.rows.filter(x=>x.situacao==='AUSENTE').length)];
      }else if(data.tipo==='PRESENCAS_SESSAO'){
        result.titulo='Presenças por sessão';result.columns=[col('sessao','Sessão'),col('participante','Participante'),col('numero_inscricao','Inscrição'),col('entrada','Entrada','datetime'),col('saida','Saída','datetime'),col('situacao','Situação','status')];result.rows=db.attendance.filter(x=>map[x.id_inscricao]&&(!data.id_sessao||x.id_sessao===data.id_sessao)).map(x=>{const ses=db.sessions.find(s=>s.id_sessao===x.id_sessao)||{};return{sessao:ses.titulo||'',participante:map[x.id_inscricao].nome_completo,numero_inscricao:map[x.id_inscricao].numero_inscricao,entrada:x.data_hora_entrada,saida:x.data_hora_saida,situacao:x.data_hora_saida?'SAIDA REGISTADA':'PRESENTE NA SESSÃO'}});result.summary=[sum('Registos',result.rows.length),sum('Sessões',new Set(result.rows.map(x=>x.sessao)).size),sum('Presentes agora',result.rows.filter(x=>!x.saida).length),sum('Saídas',result.rows.filter(x=>x.saida).length)];
      }else if(data.tipo==='ALOJAMENTO_OCUPACAO'){
        result.titulo='Ocupação dos alojamentos';result.columns=[col('alojamento','Alojamento'),col('participante','Participante'),col('numero_inscricao','Inscrição'),col('quarto','Quarto'),col('cama','Cama'),col('data_entrada','Entrada','date'),col('data_saida','Saída','date'),col('estado','Estado','status')];result.rows=db.accommodationAssignments.filter(x=>map[x.id_inscricao]&&(!data.id_alojamento||x.id_alojamento===data.id_alojamento)).map(x=>{const a=db.accommodations.find(a=>a.id_alojamento===x.id_alojamento)||{};return{alojamento:a.nome||'',participante:map[x.id_inscricao].nome_completo,numero_inscricao:map[x.id_inscricao].numero_inscricao,quarto:x.quarto,cama:x.cama,data_entrada:x.data_entrada,data_saida:x.data_saida,estado:x.estado}});result.summary=[sum('Atribuições',result.rows.length),sum('Activas',result.rows.filter(x=>['ATRIBUIDA','HOSPEDADA'].includes(x.estado)).length),sum('Alojamentos',new Set(result.rows.map(x=>x.alojamento)).size)];
      }else if(data.tipo==='ALIMENTACAO_SERVICOS'){
        result.titulo='Refeições servidas';result.columns=[col('refeicao','Refeição'),col('participante','Participante'),col('numero_inscricao','Inscrição'),col('necessidades','Necessidades alimentares'),col('data_hora','Servida em','datetime')];result.rows=db.mealDeliveries.filter(x=>map[x.id_inscricao]&&(!data.id_refeicao||x.id_refeicao===data.id_refeicao)).map(x=>{const m=db.meals.find(m=>m.id_refeicao===x.id_refeicao)||{};return{refeicao:m.nome||'',participante:map[x.id_inscricao].nome_completo,numero_inscricao:map[x.id_inscricao].numero_inscricao,necessidades:map[x.id_inscricao].necessidades_alimentares||'',data_hora:x.data_hora}});result.summary=[sum('Serviços',result.rows.length),sum('Participantes',new Set(result.rows.map(x=>x.numero_inscricao)).size),sum('Refeições',new Set(result.rows.map(x=>x.refeicao)).size)];
      }else if(data.tipo==='TRANSPORTE_PASSAGEIRAS'){
        result.titulo='Transportes e passageiras';result.columns=[col('rota','Rota'),col('data','Data','date'),col('participante','Participante'),col('numero_inscricao','Inscrição'),col('ponto_embarque','Ponto de embarque'),col('estado','Estado','status')];result.rows=db.transportAssignments.filter(x=>map[x.id_inscricao]&&(!data.id_transporte||x.id_transporte===data.id_transporte)).map(x=>{const t=db.transports.find(t=>t.id_transporte===x.id_transporte)||{};return{rota:t.rota||'',data:t.data||'',participante:map[x.id_inscricao].nome_completo,numero_inscricao:map[x.id_inscricao].numero_inscricao,ponto_embarque:x.ponto_embarque,estado:x.estado}});result.summary=[sum('Atribuições',result.rows.length),sum('Rotas',new Set(result.rows.map(x=>x.rota)).size),sum('Embarcadas',result.rows.filter(x=>x.estado==='EMBARCADA').length)];
      }else if(data.tipo==='MATERIAIS_ENTREGAS'){
        result.titulo='Materiais entregues';result.columns=[col('material','Material'),col('participante','Participante'),col('numero_inscricao','Inscrição'),col('quantidade','Quantidade','number'),col('data_entrega','Data','datetime')];result.rows=db.deliveries.filter(x=>map[x.id_inscricao]&&(!data.id_material||x.id_material===data.id_material)).map(x=>{const m=db.materials.find(m=>m.id_material===x.id_material)||{};return{material:m.nome||'',participante:map[x.id_inscricao].nome_completo,numero_inscricao:map[x.id_inscricao].numero_inscricao,quantidade:x.quantidade,data_entrega:x.data_entrega}});result.summary=[sum('Entregas',result.rows.length),sum('Quantidade',result.rows.reduce((a,x)=>a+Number(x.quantidade||0),0)),sum('Materiais',new Set(result.rows.map(x=>x.material)).size)];
      }else if(data.tipo==='CERTIFICADOS_EMITIDOS'){
        result.titulo='Certificados emitidos';result.columns=[col('codigo','Código'),col('participante','Participante'),col('numero_inscricao','Inscrição'),col('tipo','Tipo'),col('data_emissao','Emissão','datetime'),col('estado','Estado','status')];result.rows=db.certificates.filter(x=>map[x.id_inscricao]).map(x=>({codigo:x.codigo,participante:map[x.id_inscricao].nome_completo,numero_inscricao:map[x.id_inscricao].numero_inscricao,tipo:x.tipo,data_emissao:x.data_emissao,estado:x.estado}));result.summary=[sum('Certificados',result.rows.length),sum('Emitidos',result.rows.filter(x=>x.estado==='EMITIDO').length),sum('Tipos',new Set(result.rows.map(x=>x.tipo)).size)];
      }
      result.total_linhas=result.rows.length;return result;
    }
    if(action==='evaluations.list'){
      db.evaluationForms=db.evaluationForms||[];db.evaluationQuestions=db.evaluationQuestions||[];db.evaluationResponses=db.evaluationResponses||[];
      return db.evaluationForms.filter(x=>x.id_conferencia===data.id_conferencia).map(f=>({...f,total_perguntas:db.evaluationQuestions.filter(q=>q.id_formulario===f.id_formulario&&q.activo!==false).length,total_respostas:new Set(db.evaluationResponses.filter(r=>r.id_formulario===f.id_formulario).map(r=>r.grupo_resposta)).size,url_publica:`${location.origin}${location.pathname}?avaliacao=${f.token_publico}`}));
    }
    if(action==='evaluations.saveForm'){
      db.evaluationForms=db.evaluationForms||[];const now=new Date().toISOString();let form=data.id_formulario?db.evaluationForms.find(x=>x.id_formulario===data.id_formulario):null;if(form)Object.assign(form,data,{anonima:!!data.anonima,exigir_inscricao:!!data.exigir_inscricao,actualizado_em:now});else{form={...data,id_formulario:'AVF-'+Date.now(),token_publico:'demo-'+Date.now(),anonima:!!data.anonima,exigir_inscricao:!!data.exigir_inscricao,criado_em:now};db.evaluationForms.push(form);}save(db);return form;
    }
    if(action==='evaluations.questions'){db.evaluationQuestions=db.evaluationQuestions||[];return db.evaluationQuestions.filter(x=>x.id_formulario===data.id_formulario&&x.activo!==false).sort((a,b)=>Number(a.ordem)-Number(b.ordem));}
    if(action==='evaluations.saveQuestion'){db.evaluationQuestions=db.evaluationQuestions||[];let q=data.id_pergunta?db.evaluationQuestions.find(x=>x.id_pergunta===data.id_pergunta):null;if(q)Object.assign(q,data,{obrigatoria:!!data.obrigatoria,activo:true});else{q={...data,id_pergunta:'AVP-'+Date.now(),obrigatoria:!!data.obrigatoria,opcoes_json:JSON.stringify(String(data.opcoes||'').split(/\n|;/).filter(Boolean)),activo:true};db.evaluationQuestions.push(q);}save(db);return q;}
    if(action==='evaluations.deleteQuestion'){const q=(db.evaluationQuestions||[]).find(x=>x.id_pergunta===data.id_pergunta);if(q)q.activo=false;save(db);return q;}
    if(action==='evaluations.results'){const form=(db.evaluationForms||[]).find(x=>x.id_formulario===data.id_formulario)||{};const qs=(db.evaluationQuestions||[]).filter(x=>x.id_formulario===data.id_formulario&&x.activo!==false);const rs=(db.evaluationResponses||[]).filter(x=>x.id_formulario===data.id_formulario);return{form,total_respostas:new Set(rs.map(x=>x.grupo_resposta)).size,media_geral:null,questions:qs.map(q=>({id_pergunta:q.id_pergunta,texto:q.texto,tipo:q.tipo,total:0,media:null,distribuicao:[],comentarios:[]}))};}
    if(action==='evaluations.publicForm'){const form=(db.evaluationForms||[]).find(x=>x.token_publico===data.token);if(!form)throw new Error('Formulário não encontrado.');const conf=db.conferences.find(x=>x.id_conferencia===form.id_conferencia)||{};return{form,conference:conf,questions:(db.evaluationQuestions||[]).filter(x=>x.id_formulario===form.id_formulario&&x.activo!==false).map(q=>({...q,opcoes:JSON.parse(q.opcoes_json||'[]')}))};}
    if(action==='evaluations.submit'){db.evaluationResponses=db.evaluationResponses||[];const form=(db.evaluationForms||[]).find(x=>x.token_publico===data.token);const group='AVR-'+Date.now();Object.entries(data.answers||{}).forEach(([id_pergunta,value])=>db.evaluationResponses.push({grupo_resposta:group,id_formulario:form.id_formulario,id_pergunta,resposta_texto:value,data_hora:new Date().toISOString()}));save(db);return{submitted:true,mensagem_final:form.mensagem_final||'Obrigado pela sua participação.'};}
    if(action==='closure.status'){db.closures=db.closures||[];const conf=db.conferences.find(x=>x.id_conferencia===data.id_conferencia)||{};const closure=[...db.closures].reverse().find(x=>x.id_conferencia===data.id_conferencia)||null;return{conference:conf,closure,locked:conf.estado==='CONCLUIDA'};}
    if(action==='closure.checklist'){const regs=db.participants.filter(x=>x.id_conferencia===data.id_conferencia);const ss=db.sessions.filter(x=>x.id_conferencia===data.id_conferencia);const checks=[{id:'pagamentos',label:'Inscrições com saldo pendente',total:regs.filter(x=>Number(x.saldo_pendente)>0).length,severity:'warning',blocking:true},{id:'sessoes',label:'Sessões ainda não concluídas ou canceladas',total:ss.filter(x=>!['CONCLUIDA','CANCELADA'].includes(x.estado)).length,severity:'warning',blocking:true},{id:'avaliacoes',label:'Formulários de avaliação ainda abertos',total:(db.evaluationForms||[]).filter(x=>x.id_conferencia===data.id_conferencia&&x.estado==='ABERTO').length,severity:'neutral',blocking:false}];const blockers=checks.filter(x=>x.blocking).reduce((a,x)=>a+x.total,0);return{conference:db.conferences.find(x=>x.id_conferencia===data.id_conferencia),checks,blockers,warnings:checks.filter(x=>x.total).length,totals:{participantes:regs.length,presentes:regs.filter(x=>x.data_checkin).length,sessoes:ss.length,certificados:(db.certificates||[]).filter(x=>x.id_conferencia===data.id_conferencia).length,avaliacoes_recebidas:new Set((db.evaluationResponses||[]).map(x=>x.grupo_resposta)).size},can_close:blockers===0};}
    if(action==='closure.close'){db.closures=db.closures||[];const conf=db.conferences.find(x=>x.id_conferencia===data.id_conferencia);conf.estado='CONCLUIDA';const c={id_encerramento:'ENC-'+Date.now(),id_conferencia:data.id_conferencia,estado:'ENCERRADA',encerrado_em:new Date().toISOString(),justificacao:data.justificacao||''};db.closures.push(c);save(db);return{closed:true,closure:c};}
    if(action==='closure.reopen'){const conf=db.conferences.find(x=>x.id_conferencia===data.id_conferencia);conf.estado='EM_PREPARACAO';const c=[...(db.closures||[])].reverse().find(x=>x.id_conferencia===data.id_conferencia);if(c)c.estado='REABERTA';save(db);return{reopened:true};}
    if(action==='closure.generateArtifacts'){return{pasta_drive_url:'#',backup_url:'#',relatorio_final_url:'#'};}
    if(action==='dashboard.get'){
      const conference=db.conferences.find(x=>x.id_conferencia===data.id_conferencia)||db.conferences[0]||{};
      const regs=db.participants.filter(x=>!data.id_conferencia||x.id_conferencia===data.id_conferencia);
      const pays=db.payments.filter(x=>(!data.id_conferencia||x.id_conferencia===data.id_conferencia)&&x.estado==='CONFIRMADO');
      const ss=db.sessions.filter(x=>!data.id_conferencia||x.id_conferencia===data.id_conferencia);
      const dist={};regs.forEach(r=>dist[r.distrito_nome||'Sem distrito']=(dist[r.distrito_nome||'Sem distrito']||0)+1);
      const accommodations=db.accommodations.filter(x=>x.id_conferencia===data.id_conferencia);
      const accommodationIds=new Set(accommodations.map(x=>x.id_alojamento));
      const accommodationAssignments=db.accommodationAssignments.filter(x=>accommodationIds.has(x.id_alojamento)&&['ATRIBUIDA','HOSPEDADA'].includes(x.estado));
      const accommodationCapacity=accommodations.reduce((sum,x)=>sum+Number(x.capacidade||0),0);
      const transportIds=new Set(db.transports.filter(x=>x.id_conferencia===data.id_conferencia).map(x=>x.id_transporte));
      const transportAssignments=db.transportAssignments.filter(x=>transportIds.has(x.id_transporte)&&x.estado!=='CANCELADA');
      const mealIds=new Set(db.meals.filter(x=>x.id_conferencia===data.id_conferencia).map(x=>x.id_refeicao));
      const mealToday=db.mealDeliveries.filter(x=>mealIds.has(x.id_refeicao)&&String(x.data_hora||'').slice(0,10)===date(0)).length;
      const certs=db.certificates.filter(x=>x.id_conferencia===data.id_conferencia&&x.estado==='EMITIDO');
      const totalDue=regs.reduce((sum,x)=>sum+Number(x.total_devido||0),0);
      const totalCollected=pays.reduce((sum,x)=>sum+Number(x.valor||0),0);
      const totalPending=regs.reduce((sum,x)=>sum+Number(x.saldo_pendente||0),0);
      const assignedAccommodation=new Set(accommodationAssignments.map(x=>x.id_inscricao));
      const assignedTransport=new Set(transportAssignments.map(x=>x.id_inscricao));
      const checkins=regs.filter(x=>x.data_checkin||x.estado_inscricao==='PRESENTE');
      const alerts=[];
      const addAlert=(total,texto,vista,severidade='warning')=>{if(total)alerts.push({total,texto:total+' '+texto,vista,severidade});};
      addAlert(regs.filter(x=>Number(x.saldo_pendente||0)>0).length,'inscrições com valor pendente','payments');
      addAlert(regs.filter(x=>x.necessita_alojamento&&!assignedAccommodation.has(x.id_inscricao)).length,'participantes aguardam alojamento','accommodations');
      addAlert(regs.filter(x=>x.necessita_transporte&&!assignedTransport.has(x.id_inscricao)).length,'participantes aguardam transporte','transport');
      addAlert(ss.filter(x=>!x.id_moderadora&&x.estado!=='CANCELADA').length,'sessões futuras sem moderadora','sessions');
      addAlert(checkins.filter(x=>!certs.some(c=>c.id_inscricao===x.id_inscricao)).length,'participantes presentes sem certificado','certificates','neutral');
      const today=new Date().toISOString().slice(0,10);
      const dayDiff=(a,b)=>{if(!a||!b)return null;return Math.round((new Date(b+'T00:00:00')-new Date(a+'T00:00:00'))/86400000);};
      return{
        conference:{...conference,participantes:regs.length,ocupacao_percentual:Number(conference.capacidade||0)?Math.round(regs.length/Number(conference.capacidade)*100):0,dias_para_inicio:dayDiff(today,String(conference.data_inicio||'').slice(0,10)),dias_para_fim:dayDiff(today,String(conference.data_fim||'').slice(0,10))},
        kpis:{participantes:regs.length,confirmadas:regs.filter(x=>['CONFIRMADA','PRESENTE'].includes(x.estado_inscricao)).length,pendentes:regs.filter(x=>['SUBMETIDA','EM_VERIFICACAO','PENDENTE_PAGAMENTO'].includes(x.estado_inscricao)).length,presentes:checkins.length,totalDevido:totalDue,totalArrecadado:totalCollected,totalPendente:totalPending,sessoes:ss.length,pagamentosConfirmados:pays.length,pagamentosParciais:regs.filter(x=>Number(x.total_pago||0)>0&&Number(x.saldo_pendente||0)>0).length,semPagamento:regs.filter(x=>Number(x.total_devido||0)>0&&Number(x.total_pago||0)<=0).length,progressoFinanceiro:totalDue?Math.round(totalCollected/totalDue*100):0,credenciaisEntregues:regs.filter(x=>x.credencial_entregue).length,checkins:checkins.length,alojadas:accommodationAssignments.length,vagasAlojamento:Math.max(0,accommodationCapacity-accommodationAssignments.length),transporteAtribuido:new Set(transportAssignments.map(x=>x.id_inscricao)).size,refeicoesHoje:mealToday,certificadosEmitidos:new Set(certs.map(x=>x.id_inscricao)).size,materiaisEntregues:db.deliveries.filter(x=>regs.some(r=>r.id_inscricao===x.id_inscricao)).reduce((sum,x)=>sum+Number(x.quantidade||0),0)},
        alerts,
        byDistrict:Object.entries(dist).map(([nome,total])=>({nome,total})).sort((a,b)=>b.total-a.total),
        todaySessions:ss.filter(x=>x.data===today).slice(0,8),
        upcomingSessions:ss.filter(x=>String(x.data||'')>=today).slice(0,8),
        recentActivity:[
          {descricao:'Inscrição registada',utilizador:'Secretaria',data_hora:new Date().toISOString()},
          {descricao:'Pagamento confirmado',utilizador:'Tesouraria',data_hora:new Date(Date.now()-3600000).toISOString()},
          {descricao:'Alojamento atribuído',utilizador:'Logística',data_hora:new Date(Date.now()-7200000).toISOString()}
        ],
        recentPayments:pays.slice(0,6)
      };
    }
    throw new Error('Acção não implementada no sandbox: '+action);
  };
})();


/* Comunicações v2.4 — extensão isolada do sandbox. */
(function(){
  const originalSandboxApi=window.sandboxApi;
  const KEY='cmnm_sandbox_communications_v24';
  const defaults=()=>({
    templates:[
      {id_modelo:'INSCRICAO_CONFIRMADA',codigo:'INSCRICAO_CONFIRMADA',nome:'Inscrição confirmada',canal:'WHATSAPP',tipo:'INSCRICAO',assunto:'Inscrição confirmada — {conferencia}',mensagem:'Olá, {primeiro_nome}. A sua inscrição {numero_inscricao} na {conferencia} está confirmada.',activo:true},
      {id_modelo:'PAGAMENTO_PENDENTE',codigo:'PAGAMENTO_PENDENTE',nome:'Lembrete de pagamento',canal:'WHATSAPP',tipo:'PAGAMENTO',assunto:'Pagamento pendente',mensagem:'Olá, {primeiro_nome}. O seu saldo pendente é {saldo_pendente}.',activo:true},
      {id_modelo:'LEMBRETE_CONFERENCIA',codigo:'LEMBRETE_CONFERENCIA',nome:'Lembrete da conferência',canal:'EMAIL',tipo:'LEMBRETE',assunto:'Lembrete — {conferencia}',mensagem:'Cara {nome},\nA {conferencia} decorrerá em {local}.',activo:true}
    ],campaigns:[],recipients:[]
  });
  const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')||defaults();}catch{return defaults();}};
  const save=db=>localStorage.setItem(KEY,JSON.stringify(db));
  const filtersOf=data=>data.filters||(typeof data.filtros_json==='string'?(()=>{try{return JSON.parse(data.filtros_json)}catch{return{}}})():data.filtros_json)||{};
  const money=v=>new Intl.NumberFormat('pt-MZ',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v||0))+' MTn';
  const personalize=(text,r,c)=>String(text||'').replace(/\{([a-zA-Z0-9_]+)\}/g,(m,k)=>({nome:r.nome_completo,primeiro_nome:String(r.nome_completo||'').split(' ')[0],numero_inscricao:r.numero_inscricao,conferencia:c.nome,local:c.local,data_inicio:c.data_inicio,data_fim:c.data_fim,saldo_pendente:money(r.saldo_pendente),igreja:r.igreja_nome,distrito:r.distrito_nome}[k]??m));
  const audience=async data=>{
    const res=await originalSandboxApi('participants.list',{id_conferencia:data.id_conferencia,pageSize:500});let rows=res.items||[];const f=filtersOf(data);
    Object.entries({id_distrito:'id_distrito',id_igreja:'id_igreja',id_categoria:'id_categoria',estado_inscricao:'estado_inscricao',estado_pagamento:'estado_pagamento'}).forEach(([fk,rk])=>{if(f[fk])rows=rows.filter(r=>String(r[rk])===String(f[fk]));});
    if(f.saldo_pendente==='SIM')rows=rows.filter(r=>Number(r.saldo_pendente||0)>0);if(f.saldo_pendente==='NAO')rows=rows.filter(r=>Number(r.saldo_pendente||0)<=0);
    if(f.checkin==='PRESENTE')rows=rows.filter(r=>r.data_checkin||r.estado_inscricao==='PRESENTE');if(f.checkin==='AUSENTE')rows=rows.filter(r=>!r.data_checkin&&r.estado_inscricao!=='PRESENTE');
    if(f.necessita_alojamento==='SIM')rows=rows.filter(r=>r.necessita_alojamento);if(f.necessita_alojamento==='NAO')rows=rows.filter(r=>!r.necessita_alojamento);
    if(f.necessita_transporte==='SIM')rows=rows.filter(r=>r.necessita_transporte);if(f.necessita_transporte==='NAO')rows=rows.filter(r=>!r.necessita_transporte);
    if(f.search){const q=String(f.search).toLowerCase();rows=rows.filter(r=>[r.nome_completo,r.numero_inscricao,r.telefone,r.email].some(v=>String(v||'').toLowerCase().includes(q)));}
    const valid=rows.filter(r=>data.canal==='EMAIL'?r.email:r.telefone);return{rows:valid,excluded:rows.length-valid.length};
  };
  window.sandboxApi=async function(action,data={}){
    if(!String(action).startsWith('communications.'))return originalSandboxApi(action,data);
    const db=load();
    if(action==='communications.templates.list')return db.templates.filter(x=>x.activo!==false);
    if(action==='communications.templates.save'){const id=data.id_modelo||'MOD-'+Date.now();const rec={...data,id_modelo:id,codigo:data.codigo||id,activo:true};const i=db.templates.findIndex(x=>x.id_modelo===id);i>=0?db.templates[i]=rec:db.templates.push(rec);save(db);return rec;}
    if(action==='communications.preview'){const a=await audience(data);const look=await originalSandboxApi('lookups.get',{});const c=(look.conferences||[]).find(x=>x.id_conferencia===data.id_conferencia)||{};return{total:a.rows.length,excluidas_sem_contacto:a.excluded,segmento:'Segmento seleccionado',samples:a.rows.slice(0,5).map(r=>({id_inscricao:r.id_inscricao,nome:r.nome_completo,contacto:data.canal==='EMAIL'?r.email:r.telefone,assunto:personalize(data.assunto,r,c),mensagem:personalize(data.mensagem,r,c)}))};}
    if(action==='communications.save'){const a=await audience(data);const id=data.id_comunicacao||'COM-'+Date.now();const old=db.campaigns.find(x=>x.id_comunicacao===id)||{};const rec={...old,...data,id_comunicacao:id,filtros_json:JSON.stringify(filtersOf(data)),segmento:'Segmento seleccionado',destinatarios:a.rows.length,total_destinatarios:a.rows.length,enviados:old.enviados||0,falhados:old.falhados||0,estado:data.agendada_para?'AGENDADA':'RASCUNHO',criado_por:'USR-DEMO',criado_por_nome:'Administradora de Demonstração',criado_em:old.criado_em||new Date().toISOString(),actualizado_em:new Date().toISOString()};delete rec.filters;const i=db.campaigns.findIndex(x=>x.id_comunicacao===id);i>=0?db.campaigns[i]=rec:db.campaigns.push(rec);save(db);return rec;}
    if(action==='communications.list'){const rows=db.campaigns.filter(x=>!data.id_conferencia||x.id_conferencia===data.id_conferencia).sort((a,b)=>String(b.criado_em).localeCompare(String(a.criado_em)));return{items:rows,summary:{total:rows.length,rascunhos:rows.filter(x=>x.estado==='RASCUNHO').length,preparadas:rows.filter(x=>['PREPARADA','AGENDADA','PARCIAL'].includes(x.estado)).length,enviadas:rows.filter(x=>x.estado==='ENVIADA').length,destinatarios:rows.reduce((a,x)=>a+Number(x.total_destinatarios||0),0)}};}
    if(action==='communications.send'){const campaign=db.campaigns.find(x=>x.id_comunicacao===data.id_comunicacao);if(!campaign)throw new Error('Comunicação não encontrada.');let recs=db.recipients.filter(x=>x.id_comunicacao===campaign.id_comunicacao);if(!recs.length){const a=await audience({...campaign,filters:filtersOf(campaign)});const look=await originalSandboxApi('lookups.get',{});const c=(look.conferences||[]).find(x=>x.id_conferencia===campaign.id_conferencia)||{};recs=a.rows.map((r,i)=>({id_destinatario:'DEST-'+Date.now()+'-'+i,id_comunicacao:campaign.id_comunicacao,id_inscricao:r.id_inscricao,nome:r.nome_completo,canal:campaign.canal,contacto:campaign.canal==='EMAIL'?r.email:r.telefone,assunto_personalizado:personalize(campaign.assunto,r,c),mensagem_personalizada:personalize(campaign.mensagem,r,c),estado:'PENDENTE'}));db.recipients.push(...recs);}if(campaign.canal==='EMAIL')recs.forEach(r=>r.estado='ENVIADO');campaign.enviados=recs.filter(r=>r.estado==='ENVIADO').length;campaign.falhados=0;campaign.estado=campaign.canal==='EMAIL'?'ENVIADA':'PREPARADA';save(db);return{total:recs.length,enviados:campaign.enviados,falhados:0,pendentes:recs.filter(r=>r.estado==='PENDENTE').length,modo_manual:campaign.canal!=='EMAIL'};}
    if(action==='communications.recipients'){const campaign=db.campaigns.find(x=>x.id_comunicacao===data.id_comunicacao);const rows=db.recipients.filter(x=>x.id_comunicacao===data.id_comunicacao).map(r=>({...r,whatsapp_url:r.canal==='WHATSAPP'?`https://wa.me/258${String(r.contacto||'').replace(/\D/g,'').slice(-9)}?text=${encodeURIComponent(r.mensagem_personalizada||'')}`:'',sms_url:r.canal==='SMS'?`sms:${String(r.contacto||'').replace(/\D/g,'')}?body=${encodeURIComponent(r.mensagem_personalizada||'')}`:''}));return{items:rows,total:rows.length,campaign,progress:{total:rows.length,enviados:rows.filter(x=>x.estado==='ENVIADO').length,falhados:rows.filter(x=>x.estado==='ERRO').length,pendentes:rows.filter(x=>x.estado==='PENDENTE').length}};}
    if(action==='communications.markRecipient'){const r=db.recipients.find(x=>x.id_destinatario===data.id_destinatario);if(r)r.estado=data.estado;save(db);return{ok:true};}
    if(action==='communications.cancel'){const c=db.campaigns.find(x=>x.id_comunicacao===data.id_comunicacao);if(c)c.estado='CANCELADA';save(db);return{cancelled:true};}
    throw new Error('Acção de comunicação não implementada no sandbox: '+action);
  };
})();
