(function () {
  const KEY = 'cmnm_sandbox_db_v1';
  const now = new Date();
  const date = (offset) => new Date(now.getTime()+offset*86400000).toISOString().slice(0,10);
  const initial = {
    conferences:[{id_conferencia:'CONF-DEMO',codigo:'CMNM-2026',nome:'Conferência Nacional de Mulheres Nazarenas — 2026',tema:'Mulheres firmes na fé e no serviço',lema:'Chamadas para servir',texto_biblico:'Ester 4:14',local:'Cidade da Matola',data_inicio:date(20),data_fim:date(22),inscricoes_inicio:date(-30),inscricoes_fim:date(15),valor_inscricao:1500,capacidade:500,estado:'INSCRICOES_ABERTAS',contacto_nome:'Comissão Nacional',contacto_telefone:'840000000',activo:true}],
    districts:[{id_distrito:'DIST-MATOLA',codigo:'MAT',nome:'Distrito da Matola',activo:true},{id_distrito:'DIST-MAPUTO',codigo:'MAP',nome:'Distrito de Maputo',activo:true},{id_distrito:'DIST-GAZA',codigo:'GAZ',nome:'Distrito de Gaza',activo:true}],
    churches:[{id_igreja:'IGR-INFULENE',id_distrito:'DIST-MATOLA',nome:'Igreja do Nazareno em Infulene',activo:true},{id_igreja:'IGR-TCHUMENE',id_distrito:'DIST-MATOLA',nome:'Igreja do Nazareno em Tchumene',activo:true},{id_igreja:'IGR-MAPUTO',id_distrito:'DIST-MAPUTO',nome:'Igreja do Nazareno em Maputo',activo:true}],
    categories:[{id_categoria:'DELEGADA',nome:'Delegada oficial',activo:true},{id_categoria:'PARTICIPANTE',nome:'Participante',activo:true},{id_categoria:'CONVIDADA',nome:'Convidada',activo:true},{id_categoria:'MODERADORA',nome:'Moderadora',activo:true},{id_categoria:'ORADORA',nome:'Oradora',activo:true}],
    chargeTypes:[{id_tipo_cobranca:'INSCRICAO',nome:'Inscrição',activo:true},{id_tipo_cobranca:'ALOJAMENTO',nome:'Alojamento',activo:true},{id_tipo_cobranca:'CAMISETA',nome:'Camiseta',activo:true},{id_tipo_cobranca:'OUTRO',nome:'Outro',activo:true}],
    profiles:[{id_perfil:'ADMIN_GERAL',nome:'Administradora geral',activo:true},{id_perfil:'SECRETARIA',nome:'Secretaria',activo:true},{id_perfil:'TESOURARIA',nome:'Tesouraria',activo:true},{id_perfil:'PROGRAMA',nome:'Coordenação do programa',activo:true}],
    users:[{id_utilizador:'USR-DEMO',nome:'Administradora de Demonstração',username:'admin',email:'admin@demo.local',perfil_id:'ADMIN_GERAL',perfil_nome:'Administradora geral',activo:true}],
    participants:[
      {id_inscricao:'INS-1',id_participante:'PAR-1',id_conferencia:'CONF-DEMO',numero_inscricao:'CMNM-2026-00001',nome_completo:'Maria José Matola',telefone:'841234567',email:'maria@example.org',id_distrito:'DIST-MATOLA',distrito_nome:'Distrito da Matola',id_igreja:'IGR-INFULENE',igreja_nome:'Igreja do Nazareno em Infulene',id_categoria:'DELEGADA',categoria_nome:'Delegada oficial',total_devido:1500,total_pago:1500,saldo_pendente:0,estado_pagamento:'PAGO',estado_inscricao:'CONFIRMADA',necessita_alojamento:true,necessita_transporte:false},
      {id_inscricao:'INS-2',id_participante:'PAR-2',id_conferencia:'CONF-DEMO',numero_inscricao:'CMNM-2026-00002',nome_completo:'Ana Carla Nhampossa',telefone:'851234567',email:'ana@example.org',id_distrito:'DIST-MAPUTO',distrito_nome:'Distrito de Maputo',id_igreja:'IGR-MAPUTO',igreja_nome:'Igreja do Nazareno em Maputo',id_categoria:'PARTICIPANTE',categoria_nome:'Participante',total_devido:1500,total_pago:700,saldo_pendente:800,estado_pagamento:'PARCIAL',estado_inscricao:'SUBMETIDA',necessita_alojamento:false,necessita_transporte:true},
      {id_inscricao:'INS-3',id_participante:'PAR-3',id_conferencia:'CONF-DEMO',numero_inscricao:'CMNM-2026-00003',nome_completo:'Teresa Alberto Cossa',telefone:'861234567',email:'teresa@example.org',id_distrito:'DIST-MATOLA',distrito_nome:'Distrito da Matola',id_igreja:'IGR-TCHUMENE',igreja_nome:'Igreja do Nazareno em Tchumene',id_categoria:'CONVIDADA',categoria_nome:'Convidada',total_devido:0,total_pago:0,saldo_pendente:0,estado_pagamento:'ISENTO',estado_inscricao:'PRESENTE',necessita_alojamento:true,necessita_transporte:true}
    ],
    payments:[{id_pagamento:'PAG-1',id_conferencia:'CONF-DEMO',id_inscricao:'INS-1',participante_nome:'Maria José Matola',numero_inscricao:'CMNM-2026-00001',id_tipo_cobranca:'INSCRICAO',tipo_cobranca_nome:'Inscrição',valor:1500,metodo_pagamento:'M-PESA',referencia:'MP123456',data_pagamento:date(-2),estado:'CONFIRMADO',numero_recibo:'REC-CMNM-2026-000001'},{id_pagamento:'PAG-2',id_conferencia:'CONF-DEMO',id_inscricao:'INS-2',participante_nome:'Ana Carla Nhampossa',numero_inscricao:'CMNM-2026-00002',id_tipo_cobranca:'INSCRICAO',tipo_cobranca_nome:'Inscrição',valor:700,metodo_pagamento:'NUMERARIO',referencia:'',data_pagamento:date(-1),estado:'SUBMETIDO',numero_recibo:''}],
    intervenients:[{id_interveniente:'INT-1',nome:'Rev. Isabel Mucavele',tipo:'MODERADORA',titulo_funcao:'Coordenadora nacional',telefone:'840000001',email:'isabel@example.org',confirmacao:'CONFIRMADA',activo:true},{id_interveniente:'INT-2',nome:'Dra. Lúcia Macamo',tipo:'ORADORA',titulo_funcao:'Palestrante',telefone:'840000002',email:'lucia@example.org',confirmacao:'CONFIRMADA',activo:true}],
    sessions:[{id_sessao:'PROG-1',id_conferencia:'CONF-DEMO',titulo:'Culto de abertura',tipo:'ABERTURA',data:date(20),hora_inicio:'09:00',hora_fim:'10:30',local:'Auditório principal',capacidade:500,id_moderadora:'INT-1',moderadora_nome:'Rev. Isabel Mucavele',id_oradora:'INT-2',oradora_nome:'Dra. Lúcia Macamo',estado:'CONFIRMADA'},{id_sessao:'PROG-2',id_conferencia:'CONF-DEMO',titulo:'Liderança e serviço cristão',tipo:'PALESTRA',data:date(20),hora_inicio:'11:00',hora_fim:'12:30',local:'Auditório principal',capacidade:500,id_moderadora:'INT-1',moderadora_nome:'Rev. Isabel Mucavele',id_oradora:'INT-2',oradora_nome:'Dra. Lúcia Macamo',estado:'PROGRAMADA'}]
  };
  function load(){const raw=localStorage.getItem(KEY);if(raw)return JSON.parse(raw);localStorage.setItem(KEY,JSON.stringify(initial));return JSON.parse(JSON.stringify(initial));}
  function save(db){localStorage.setItem(KEY,JSON.stringify(db));}
  function id(prefix){return prefix+'-'+Math.random().toString(36).slice(2,10).toUpperCase();}
  const page=(items)=>({items,total:items.length,page:1,pageSize:500,pages:1});
  window.sandboxApi=async function(action,data){
    await new Promise(r=>setTimeout(r,180)); const db=load(); data=data||{};
    if(action==='system.health')return{app:'Sandbox',version:'1.0.0',status:'online'};
    if(action==='auth.login'){if(data.username==='admin'&&data.password==='admin')return{token:'sandbox-token',expiresAt:date(1),user:db.users[0],permissions:['*']};throw new Error('Utilizador ou palavra-passe inválidos.');}
    if(action==='auth.me')return{user:db.users[0],permissions:['*']}; if(action==='auth.logout')return{loggedOut:true};
    if(action==='lookups.get')return{districts:db.districts,churches:db.churches,categories:db.categories,chargeTypes:db.chargeTypes,profiles:db.profiles,conferences:db.conferences,intervenients:db.intervenients,selectedConferenceId:db.conferences[0]?.id_conferencia||''};
    if(action==='conferences.list')return page(db.conferences);
    if(action==='conferences.save'){let r;if(data.id_conferencia){r=db.conferences.find(x=>x.id_conferencia===data.id_conferencia);Object.assign(r,data);}else{r={...data,id_conferencia:id('CONF'),activo:true};db.conferences.push(r);}save(db);return r;}
    if(action==='participants.list'){let rows=db.participants.filter(x=>!data.id_conferencia||x.id_conferencia===data.id_conferencia);if(data.search){const q=data.search.toLowerCase();rows=rows.filter(x=>[x.nome_completo,x.telefone,x.numero_inscricao,x.igreja_nome].some(v=>String(v||'').toLowerCase().includes(q)));}if(data.estado_inscricao)rows=rows.filter(x=>x.estado_inscricao===data.estado_inscricao);return page(rows);}
    if(action==='participants.create'){const d=db.districts.find(x=>x.id_distrito===data.id_distrito),c=db.churches.find(x=>x.id_igreja===data.id_igreja),cat=db.categories.find(x=>x.id_categoria===data.id_categoria);const n=db.participants.length+1;const r={...data,id_inscricao:id('INS'),id_participante:id('PAR'),numero_inscricao:'CMNM-2026-'+String(n).padStart(5,'0'),distrito_nome:d?.nome||'',igreja_nome:c?.nome||'',categoria_nome:cat?.nome||'',total_devido:Number(data.total_devido||1500),total_pago:0,saldo_pendente:Number(data.total_devido||1500),estado_pagamento:Number(data.total_devido||1500)>0?'PENDENTE':'ISENTO',estado_inscricao:data.estado_inscricao||'SUBMETIDA'};db.participants.push(r);save(db);return{participant:r,registration:r};}
    if(action==='participants.update'){const r=db.participants.find(x=>x.id_inscricao===data.id_inscricao);Object.assign(r,data);save(db);return{updated:true};}
    if(action==='participants.setStatus'){const r=db.participants.find(x=>x.id_inscricao===data.id_inscricao);r.estado_inscricao=data.estado_inscricao;save(db);return r;}
    if(action==='participants.checkin'){const r=db.participants.find(x=>x.id_inscricao===data.id_inscricao);r.estado_inscricao='PRESENTE';r.data_checkin=new Date().toISOString();save(db);return r;}
    if(action==='payments.list'){let rows=db.payments.filter(x=>!data.id_conferencia||x.id_conferencia===data.id_conferencia);if(data.estado)rows=rows.filter(x=>x.estado===data.estado);return page(rows);}
    if(action==='payments.create'){const p=db.participants.find(x=>x.id_inscricao===data.id_inscricao);const r={...data,id_pagamento:id('PAG'),participante_nome:p?.nome_completo||'',numero_inscricao:p?.numero_inscricao||'',tipo_cobranca_nome:db.chargeTypes.find(x=>x.id_tipo_cobranca===data.id_tipo_cobranca)?.nome||data.descricao,valor:Number(data.valor),estado:'SUBMETIDO'};db.payments.push(r);save(db);return r;}
    if(action==='payments.confirm'){const r=db.payments.find(x=>x.id_pagamento===data.id_pagamento);r.estado='CONFIRMADO';r.numero_recibo=r.numero_recibo||'REC-DEMO-'+String(db.payments.indexOf(r)+1).padStart(6,'0');const p=db.participants.find(x=>x.id_inscricao===r.id_inscricao);if(p){p.total_pago=Number(p.total_pago||0)+Number(r.valor);p.saldo_pendente=Math.max(0,p.total_devido-p.total_pago);p.estado_pagamento=p.saldo_pendente===0?'PAGO':'PARCIAL';}save(db);return r;}
    if(action==='payments.reject'){const r=db.payments.find(x=>x.id_pagamento===data.id_pagamento);r.estado='REJEITADO';r.motivo_rejeicao=data.motivo_rejeicao;save(db);return r;}
    if(action==='sessions.list')return page(db.sessions.filter(x=>!data.id_conferencia||x.id_conferencia===data.id_conferencia));
    if(action==='sessions.save'){let r;if(data.id_sessao){r=db.sessions.find(x=>x.id_sessao===data.id_sessao);Object.assign(r,data);}else{r={...data,id_sessao:id('PROG')};db.sessions.push(r);}const m=db.intervenients.find(x=>x.id_interveniente===r.id_moderadora),o=db.intervenients.find(x=>x.id_interveniente===r.id_oradora);r.moderadora_nome=m?.nome||'';r.oradora_nome=o?.nome||'';save(db);return r;}
    if(action==='intervenients.list')return page(db.intervenients);
    if(action==='intervenients.save'){let r;if(data.id_interveniente){r=db.intervenients.find(x=>x.id_interveniente===data.id_interveniente);Object.assign(r,data);}else{r={...data,id_interveniente:id('INT'),activo:true};db.intervenients.push(r);}save(db);return r;}
    if(action==='users.list')return page(db.users);
    if(action==='users.create'){const r={...data,id_utilizador:id('USR'),perfil_nome:db.profiles.find(x=>x.id_perfil===data.perfil_id)?.nome||data.perfil_id,activo:true};delete r.password;db.users.push(r);save(db);return r;}
    if(action==='users.update'){const r=db.users.find(x=>x.id_utilizador===data.id_utilizador);Object.assign(r,data);save(db);return r;}
    if(action==='dashboard.get'){const regs=db.participants.filter(x=>!data.id_conferencia||x.id_conferencia===data.id_conferencia),pays=db.payments.filter(x=>(!data.id_conferencia||x.id_conferencia===data.id_conferencia)&&x.estado==='CONFIRMADO'),ss=db.sessions.filter(x=>!data.id_conferencia||x.id_conferencia===data.id_conferencia);const dist={};regs.forEach(r=>dist[r.distrito_nome||'Sem distrito']=(dist[r.distrito_nome||'Sem distrito']||0)+1);return{kpis:{participantes:regs.length,confirmadas:regs.filter(x=>['CONFIRMADA','PRESENTE'].includes(x.estado_inscricao)).length,pendentes:regs.filter(x=>['SUBMETIDA','EM_VERIFICACAO','PENDENTE_PAGAMENTO'].includes(x.estado_inscricao)).length,presentes:regs.filter(x=>x.estado_inscricao==='PRESENTE').length,totalDevido:regs.reduce((s,x)=>s+Number(x.total_devido||0),0),totalArrecadado:pays.reduce((s,x)=>s+Number(x.valor||0),0),totalPendente:regs.reduce((s,x)=>s+Number(x.saldo_pendente||0),0),sessoes:ss.length},byDistrict:Object.entries(dist).map(([nome,total])=>({nome,total})),upcomingSessions:ss.slice(0,6),recentPayments:pays.slice(0,6)};}
    throw new Error('Acção não implementada no sandbox: '+action);
  };
})();
